### PR TITLE
added vip/pct

### PR DESCRIPTION
**Pull request by klotterc**

### CODE REVIEW

**Comment by Redexxes** [comment]
Made a GitHub hosting for this and tried it out myself, it's working good :)
I was actually in the process of attempting to update it myself, and I had just added the job icons when I saw that this just got submitted.

**Comment by cglatot** [comment]
Given that @hibiyasleep hasn't made any updates in the past 2 years to Kagerou, I probably wouldn't hold my breath about this PR being added any time soon, so you might want to host it yourself anyway.

**Comment by hibiyasleep** [comment]
Sorry for late!!! I'll merge this first!!

**Comment by cglatot** [comment]
Well collar me wrong! Thanks Hibiya! Much appreciated :D

**Comment by Redexxes** [comment]
Thanks!

**Pull request merged**
